version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: trade-journal-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: trade-journal-server
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/trade_journal
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: trade-journal-client
    ports:
      - "3001:3000" # Next.js runs on 3000 internally
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:
